### ISSUE TITLE
手机内置存储作为U盘 识别不到数据源的文件

### ISSUE THREAD

**Issue by jiangyingjun** [outofmemo/UMS-Interface#3]
你好！问题如题 多次点击启动/关闭   挂载/卸载都不好使。求教怎么解决。
手机型号：三星note2.。
其他人如果有遇到该问题的 可以一起讨论下呀

**Comment by outofmemo** [comment]
具体是什么情况,如何使用的,显示什么信息,PC端显示什么

已知使用三星芯片的手机使用UMS时默认会作为CD ROM, 由于没有实机来测试,暂未解决.

**Comment by jiangyingjun** [comment]
抱歉 没描述清楚问题。上面那个问题解决了    出现的原因是： 在单片机里面 读不到U盘挂载路径的数据。让我误以为识别不到。其实是读到镜像文件了。现在的问题是：在windows里面向识别到的镜像文件中放文件。但是在UMS-Interface项目中显示的数据挂载点找不到放进去的文件。经测试我认为文件被封到了镜像文件中。所以想问下 能不能在手机端找到镜像文件中保存数据的目录。并且进行操作

**Comment by outofmemo** [comment]
在windows 中向里面写入文件后,文件实际已被写进去了.但分区内容被外部(相对于Android linux内核)修改,linux内核并不知到文件系统已经发生变动,故在手机上可能不能立即看到文件,这时将分区(镜像)卸载,然后重新挂载即可

**Comment by jiangyingjun** [comment]
很感谢！！问题解决了。 过程：我从手机文件系统复制文件到数据源文件夹中。挂载卸载不好用。但是通过命令复制文件到数据源文件夹中就可以啦
