### ISSUE TITLE
UMS fail:MassStorageUnit  is not ready!

### ISSUE THREAD

**Issue by Freed-Wu** [outofmemo/UMS-Interface#5]
This is log:
[ums_log.tar.gz](https://github.com/outofmemo/UMS-Interface/files/5701061/ums_log.tar.gz)

Thanks!

**Comment by Freed-Wu** [comment]
I have reinstalled OS on my phone: install new OS, install twrp, install
  magisk, install ums, but it always return UMS fail. my phone is Oppo R15x,
  and OS is color OS c.14 (2140).

**Comment by Freed-Wu** [comment]
i have read the repo. The variable mLunPath
  `/sys/devices/virtual/android_usb/android0/f_mass_storage/lun` doesn't exist
  in my phone, which results in this error. excuse me. what is this path? is it necessary? how can i do to solve it? thanks!

**Comment by Freed-Wu** [comment]
See <https://android.stackexchange.com/a/205559/218526>, this app doesn't support new android device.

**Comment by outofmemo** [comment]
Are you using the latest version of the app?

**Comment by outofmemo** [comment]
You can try this https://raw.githubusercontent.com/outofmemo/UMS-Interface/master/update/app-release.apk

**Comment by Freed-Wu** [comment]
Oh my god. it can work! Sooooo thanks!
